services:
  - type: worker
    name: anonx-music-bot
    runtime: docker # ဒီမှာ docker လို့ ရေးထားရင် လုံလောက်ပါပြီ
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: LOGGER_ID
        sync: false
